def mix(a: int, b: int) -> int:
    return a ^ b

def prune(a: int) -> int:
    return a % 16777216

def next_secret_number(number: int) -> int:
    result = prune(mix(number, number * 64))
    result = prune(mix(result, result // 32))
    result = prune(mix(result, result * 2048))
    return result

STEPS = 2000

with open("input.txt", "r") as f:
    lines = f.readlines()
numbers = [int(line) for line in lines]

total = 0
for number in numbers:
    n = number
    for _ in range(STEPS):
        n = next_secret_number(n)
    total += n
print(f"The sum of the {STEPS}th secret number generated by each buyer is {total}")